services:
  node00:
    environment:
      ConnectDelaySeconds: "9"
      ConnectNodes__0: "node01"
      ConnectNodes__1: "node10"
      ConnectNodes__2: "node11"
      ConnectNodes__3: "node20"
      PingAllConnectedNodes: "false"
      RunDurationSeconds: "${PNET_MESH_E2E_RUN_SECONDS:-30}"
  node01:
    environment:
      ConnectDelaySeconds: "3"
      ConnectNodes__0: "node00"
      PingAllConnectedNodes: "false"
      PingNodes__0: "node00"
      RunDurationSeconds: "${PNET_MESH_E2E_RUN_SECONDS:-30}"
  node10:
    environment:
      ConnectDelaySeconds: "3"
      ConnectNodes__0: "node00"
      PingAllConnectedNodes: "false"
      PingNodes__0: "node00"
      RunDurationSeconds: "${PNET_MESH_E2E_RUN_SECONDS:-30}"
    extra_hosts:
    - "host.docker.internal:host-gateway"
  node11:
    environment:
      ConnectDelaySeconds: "3"
      ConnectNodes__0: "node00"
      PingAllConnectedNodes: "false"
      PingNodes__0: "node00"
      RunDurationSeconds: "${PNET_MESH_E2E_RUN_SECONDS:-30}"
    extra_hosts:
    - "host.docker.internal:host-gateway"
  node20:
    environment:
      ConnectDelaySeconds: "6"
      ConnectNodes__0: "node00"
      ConnectNodes__1: "node21"
      PingAllConnectedNodes: "false"
      PingNodes__0: "node00"
      RunDurationSeconds: "${PNET_MESH_E2E_RUN_SECONDS:-30}"
    extra_hosts:
    - "host.docker.internal:host-gateway"
  node21:
    environment:
      ConnectDelaySeconds: "3"
      ConnectNodes__0: "node20"
      PingAllConnectedNodes: "false"
      PingNodes__0: "node20"
      RunDurationSeconds: "${PNET_MESH_E2E_RUN_SECONDS:-30}"
