// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pnet/type/proto_metadata.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PNet.Protos {

  /// <summary>Holder for reflection information generated from pnet/type/proto_metadata.proto</summary>
  public static partial class ProtoMetadataReflection {

    #region Descriptor
    /// <summary>File descriptor for pnet/type/proto_metadata.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoMetadataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5wbmV0L3R5cGUvcHJvdG9fbWV0YWRhdGEucHJvdG8SCXBuZXQudHlwZRoZ",
            "Z29vZ2xlL2FwaS9yZXNvdXJjZS5wcm90byLSAQoNUHJvdG9NZXRhZGF0YRIU",
            "CgxwYXlsb2FkX3NpemUYASABKA0SFwoPY29tcHJlc3NlZF9zaXplGAIgASgN",
            "Eh4KDWRpY3Rpb25hcnlfaWQYAyABKA1IAFIFZGljSWQSOQoKZGljdGlvbmFy",
            "eRgEIAEoCUIe+kEbChlwbmV0LnR5cGUvUHJvdG9EaWN0aW9uYXJ5SABSA2Rp",
            "YxINCgVmbGFncxgKIAEoDRIWCg5zY2hlbWFfdmVyc2lvbhgLIAEoBUIQCg5k",
            "aWN0aW9uYXJ5X3JlZkIOqgILUE5ldC5Qcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.ResourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PNet.Protos.ProtoMetadata), global::PNet.Protos.ProtoMetadata.Parser, new[]{ "PayloadSize", "CompressedSize", "DictionaryId", "Dictionary", "Flags", "SchemaVersion" }, new[]{ "DictionaryRef" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Metadata for stored or transfered payload
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProtoMetadata : pb::IMessage<ProtoMetadata>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtoMetadata> _parser = new pb::MessageParser<ProtoMetadata>(() => new ProtoMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtoMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PNet.Protos.ProtoMetadataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoMetadata(ProtoMetadata other) : this() {
      payloadSize_ = other.payloadSize_;
      compressedSize_ = other.compressedSize_;
      flags_ = other.flags_;
      schemaVersion_ = other.schemaVersion_;
      switch (other.DictionaryRefCase) {
        case DictionaryRefOneofCase.DictionaryId:
          DictionaryId = other.DictionaryId;
          break;
        case DictionaryRefOneofCase.Dictionary:
          Dictionary = other.Dictionary;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoMetadata Clone() {
      return new ProtoMetadata(this);
    }

    /// <summary>Field number for the "payload_size" field.</summary>
    public const int PayloadSizeFieldNumber = 1;
    private uint payloadSize_;
    /// <summary>
    /// Size of the original payload in bytes (uncompressed).
    /// store only for compressed payload
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PayloadSize {
      get { return payloadSize_; }
      set {
        payloadSize_ = value;
      }
    }

    /// <summary>Field number for the "compressed_size" field.</summary>
    public const int CompressedSizeFieldNumber = 2;
    private uint compressedSize_;
    /// <summary>
    /// Size of the stored payload in bytes (after compression if used).
    /// reset before storage and set it back on read
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CompressedSize {
      get { return compressedSize_; }
      set {
        compressedSize_ = value;
      }
    }

    /// <summary>Field number for the "dictionary_id" field.</summary>
    public const int DictionaryIdFieldNumber = 3;
    /// <summary>
    /// ID of the compression dictionary used.
    /// 0 = no dictionary / uncompressed
    /// 1 = Zstd without dictionary
    /// 2 = LZ4 without dictionary
    /// >= 128 = user-defined dictionaries
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DictionaryId {
      get { return HasDictionaryId ? (uint) dictionaryRef_ : 0; }
      set {
        dictionaryRef_ = value;
        dictionaryRefCase_ = DictionaryRefOneofCase.DictionaryId;
      }
    }
    /// <summary>Gets whether the "dictionary_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDictionaryId {
      get { return dictionaryRefCase_ == DictionaryRefOneofCase.DictionaryId; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "dictionary_id" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDictionaryId() {
      if (HasDictionaryId) {
        ClearDictionaryRef();
      }
    }

    /// <summary>Field number for the "dictionary" field.</summary>
    public const int DictionaryFieldNumber = 4;
    /// <summary>
    /// resource name of dictionary for compression usage
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Dictionary {
      get { return HasDictionary ? (string) dictionaryRef_ : ""; }
      set {
        dictionaryRef_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        dictionaryRefCase_ = DictionaryRefOneofCase.Dictionary;
      }
    }
    /// <summary>Gets whether the "dictionary" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDictionary {
      get { return dictionaryRefCase_ == DictionaryRefOneofCase.Dictionary; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "dictionary" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDictionary() {
      if (HasDictionary) {
        ClearDictionaryRef();
      }
    }

    /// <summary>Field number for the "flags" field.</summary>
    public const int FlagsFieldNumber = 10;
    private uint flags_;
    /// <summary>
    ///bitfield:
    ///bit 0: padding bit (force 1 byte varint, should be set if a single bit update is expected)
    ///bit 1: uncompressable (payload is not compressible or should not be compressed)
    ///2-31: reserved (future expansion)
    ///ideas: temporary, archived
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Flags {
      get { return flags_; }
      set {
        flags_ = value;
      }
    }

    /// <summary>Field number for the "schema_version" field.</summary>
    public const int SchemaVersionFieldNumber = 11;
    private int schemaVersion_;
    /// <summary>
    ///schema_version = 0: Payload is bare Resource
    ///schema_version = 1: Payload is StoredResource wrapper (future breaking change)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SchemaVersion {
      get { return schemaVersion_; }
      set {
        schemaVersion_ = value;
      }
    }

    private object dictionaryRef_;
    /// <summary>Enum of possible cases for the "dictionary_ref" oneof.</summary>
    public enum DictionaryRefOneofCase {
      None = 0,
      DictionaryId = 3,
      Dictionary = 4,
    }
    private DictionaryRefOneofCase dictionaryRefCase_ = DictionaryRefOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DictionaryRefOneofCase DictionaryRefCase {
      get { return dictionaryRefCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDictionaryRef() {
      dictionaryRefCase_ = DictionaryRefOneofCase.None;
      dictionaryRef_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtoMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtoMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PayloadSize != other.PayloadSize) return false;
      if (CompressedSize != other.CompressedSize) return false;
      if (DictionaryId != other.DictionaryId) return false;
      if (Dictionary != other.Dictionary) return false;
      if (Flags != other.Flags) return false;
      if (SchemaVersion != other.SchemaVersion) return false;
      if (DictionaryRefCase != other.DictionaryRefCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PayloadSize != 0) hash ^= PayloadSize.GetHashCode();
      if (CompressedSize != 0) hash ^= CompressedSize.GetHashCode();
      if (HasDictionaryId) hash ^= DictionaryId.GetHashCode();
      if (HasDictionary) hash ^= Dictionary.GetHashCode();
      if (Flags != 0) hash ^= Flags.GetHashCode();
      if (SchemaVersion != 0) hash ^= SchemaVersion.GetHashCode();
      hash ^= (int) dictionaryRefCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PayloadSize != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PayloadSize);
      }
      if (CompressedSize != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(CompressedSize);
      }
      if (HasDictionaryId) {
        output.WriteRawTag(24);
        output.WriteUInt32(DictionaryId);
      }
      if (HasDictionary) {
        output.WriteRawTag(34);
        output.WriteString(Dictionary);
      }
      if (Flags != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(Flags);
      }
      if (SchemaVersion != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(SchemaVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PayloadSize != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PayloadSize);
      }
      if (CompressedSize != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(CompressedSize);
      }
      if (HasDictionaryId) {
        output.WriteRawTag(24);
        output.WriteUInt32(DictionaryId);
      }
      if (HasDictionary) {
        output.WriteRawTag(34);
        output.WriteString(Dictionary);
      }
      if (Flags != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(Flags);
      }
      if (SchemaVersion != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(SchemaVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PayloadSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PayloadSize);
      }
      if (CompressedSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CompressedSize);
      }
      if (HasDictionaryId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DictionaryId);
      }
      if (HasDictionary) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Dictionary);
      }
      if (Flags != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Flags);
      }
      if (SchemaVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SchemaVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtoMetadata other) {
      if (other == null) {
        return;
      }
      if (other.PayloadSize != 0) {
        PayloadSize = other.PayloadSize;
      }
      if (other.CompressedSize != 0) {
        CompressedSize = other.CompressedSize;
      }
      if (other.Flags != 0) {
        Flags = other.Flags;
      }
      if (other.SchemaVersion != 0) {
        SchemaVersion = other.SchemaVersion;
      }
      switch (other.DictionaryRefCase) {
        case DictionaryRefOneofCase.DictionaryId:
          DictionaryId = other.DictionaryId;
          break;
        case DictionaryRefOneofCase.Dictionary:
          Dictionary = other.Dictionary;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PayloadSize = input.ReadUInt32();
            break;
          }
          case 16: {
            CompressedSize = input.ReadUInt32();
            break;
          }
          case 24: {
            DictionaryId = input.ReadUInt32();
            break;
          }
          case 34: {
            Dictionary = input.ReadString();
            break;
          }
          case 80: {
            Flags = input.ReadUInt32();
            break;
          }
          case 88: {
            SchemaVersion = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PayloadSize = input.ReadUInt32();
            break;
          }
          case 16: {
            CompressedSize = input.ReadUInt32();
            break;
          }
          case 24: {
            DictionaryId = input.ReadUInt32();
            break;
          }
          case 34: {
            Dictionary = input.ReadString();
            break;
          }
          case 80: {
            Flags = input.ReadUInt32();
            break;
          }
          case 88: {
            SchemaVersion = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
